# Copyright Contributors to the Open Cluster Management project

# pre hook used to install the OADP Operator, using the {{ .Values.oadpOperator.namespace }} namespace
apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
  name: {{ .Values.oadpOperator.name }}-subscription
  namespace: {{ .Release.Namespace }}
  annotations:
    "helm.sh/hook": pre-install
    "helm.sh/hook-weight": "-1"
    "helm.sh/resource-policy": delete
spec:
  channel: {{ .Values.oadpOperator.channel }}
  startingCSV: {{ .Values.oadpOperator.startingCSV }}
  config:
    resources: {}
{{- with .Values.hubconfig.nodeSelector }}
    nodeSelector:
{{ toYaml . | indent 6 }}
{{- end }}
  installPlanApproval: {{ .Values.oadpOperator.installPlanApproval}}
  name: {{ .Values.oadpOperator.name }}
  source: {{ .Values.oadpOperator.source }}
  sourceNamespace: {{ .Values.oadpOperator.sourceNamespace }}