# Copyright Contributors to the Open Cluster Management project

# pre hook used to install the OADP Operator, using the {{ .Values.oadpOperator.namespace }} namespace
apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
  name: {{ .Values.oadpOperator.name }}-subscription
  namespace: {{ .Release.Namespace }}
  annotations:
    "helm.sh/hook": pre-install
    "helm.sh/hook-weight": "-1"
    "helm.sh/resource-policy": keep # hook resources that must never be deleted
spec:
  channel: {{ .Values.oadpOperator.channel }}
  startingCSV: {{ .Values.oadpOperator.startingCSV }}
  config:
    resources: {}
{{- with .Values.hubconfig.nodeSelector }}
    nodeSelector:
{{ toYaml . | indent 6 }}
{{- end }}
    tolerations:
    - key: dedicated
      operator: Exists
      effect: NoSchedule
    - effect: NoSchedule 
      key: node-role.kubernetes.io/infra 
      operator: Exists
  installPlanApproval: Automatic
  name: {{ .Values.oadpOperator.name }}
  source: {{ .Values.oadpOperator.source }}
  sourceNamespace: {{ .Values.oadpOperator.sourceNamespace }}